### ISSUE TITLE
load failures

### ISSUE THREAD

**Issue by Tcll** [libertyernie/brawltools#169] opened 2018-01-26 00:28 UTC
```
tcll@tcll-AY589AAR-ABA-a4317c:~/Programs/win/BB078$ /opt/wine-staging/bin/wine /home/tcll/Programs/win/BB078/BrawlBox.exe
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"configSections" in state 2
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"sectionGroup" in state 6
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"section" in state 6
fixme:mscoree:parse_supported_runtime sku=L".NETFramework,Version=v4.0" not implemented
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"applicationSettings" in state 2
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"BrawlBox.Properties.Settings" in state 6
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"setting" in state 6
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"value" in state 6
fixme:mscoree:parse_probing privatePath=L"Lib" not implemented

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'BrawlLib, Version=0.25.6288.24886, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'BrawlLib, Version=0.25.6288.24886, Culture=neutral, PublicKeyToken=null'
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'BrawlLib, Version=0.25.6288.24886, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'BrawlLib, Version=0.25.6288.24886, Culture=neutral, PublicKeyToken=null'
```
this is just a raw extract and run
it seems to load when the files in `./Lib/` are brought to `./`, but that gives me an expected "path changed" error dialog.

I'm running Xubuntu 16.04.3 with wine-staging 2.21 under it's latest libraries

I believe I was able to use v0.77 just fine, but recently my HDD died and I lost that.

EDIT: update
works on WinXP, maybe this is just a wine thing

**Comment by Sammi-Husky** [comment] 2018-07-21 01:01
Duplicate of #185 (resolved)

**Closed by Sammi-Husky** 2018-07-21 01:01 UTC
